name = "ReverseOsmosis"
uuid = "90c5803b-0a13-4606-b42d-93b6628f5af1"
authors = ["Yumbang <59196217+Yumbang@users.noreply.github.com>"]
version = "0.2.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DataFrames = "1.7.0"
Unitful = "1.22.0"
julia = "1.10"
